Importing Libraries

In [12]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd


Importing Dataset

In [13]:
dataset =  pd.read_csv('Data.csv')
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:,-1].values

In [14]:
print(x)


[[  14.96   41.76 1024.07   73.17]
 [  25.18   62.96 1020.04   59.08]
 [   5.11   39.4  1012.16   92.14]
 ...
 [  31.32   74.33 1012.92   36.48]
 [  24.48   69.45 1013.86   62.39]
 [  21.6    62.52 1017.23   67.87]]


In [15]:
print(y)

[463.26 444.37 488.56 ... 429.57 435.74 453.28]


Taking Care Of Missing data

In [16]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan,strategy="mean")
imputer.fit(x[:,1:3])
imputer.transform(x[:,1:3])
x[:,1:3] = imputer.transform(x[:,1:3])

In [17]:
print(x)

[[  14.96   41.76 1024.07   73.17]
 [  25.18   62.96 1020.04   59.08]
 [   5.11   39.4  1012.16   92.14]
 ...
 [  31.32   74.33 1012.92   36.48]
 [  24.48   69.45 1013.86   62.39]
 [  21.6    62.52 1017.23   67.87]]


Encoding Categorical Data

Encoding Independent Variable

In [18]:
print(y)

[463.26 444.37 488.56 ... 429.57 435.74 453.28]


Splitting the dataset into Training Set and testing Set

In [19]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size= 0.2, random_state=1)

In [20]:
print(x_train)

[[   6.61   38.91 1015.77   92.31]
 [  22.72   65.61 1014.64   70.53]
 [  10.06   39.61 1018.22   70.22]
 ...
 [  18.59   39.54 1008.56   68.61]
 [  22.96   45.01 1012.21   50.81]
 [  20.5    49.69 1009.6    70.81]]


In [21]:
print(x_test)

[[  17.93   44.63 1003.54   87.41]
 [  16.34   42.28 1008.08   52.8 ]
 [  25.97   70.32 1007.48   57.01]
 ...
 [  10.68   38.38 1020.79   72.33]
 [  34.03   73.56 1006.49   51.07]
 [  15.28   44.58 1016.45   83.07]]


In [22]:
print(y_train)

[484.32 449.04 471.86 ... 462.56 450.37 452.94]


In [23]:
print(y_test)

[458.96 463.29 435.27 ... 476.22 440.29 467.92]


Feature Scaling

In [24]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:, 3:] = sc.fit_transform(x_train[: , 3:])
x_test[:, 3:] = sc.transform(x_test[: , 3:])


In [25]:
print(x_test)

[[ 1.79300000e+01  4.46300000e+01  1.00354000e+03  9.65947020e-01]
 [ 1.63400000e+01  4.22800000e+01  1.00808000e+03 -1.41293590e+00]
 [ 2.59700000e+01  7.03200000e+01  1.00748000e+03 -1.12356586e+00]
 ...
 [ 1.06800000e+01  3.83800000e+01  1.02079000e+03 -7.05613447e-02]
 [ 3.40300000e+01  7.35600000e+01  1.00649000e+03 -1.53184568e+00]
 [ 1.52800000e+01  4.45800000e+01  1.01645000e+03  6.67641562e-01]]


In [26]:
print(x_train)

[[ 6.61000000e+00  3.89100000e+01  1.01577000e+03  1.30274350e+00]
 [ 2.27200000e+01  6.56100000e+01  1.01464000e+03 -1.94282502e-01]
 [ 1.00600000e+01  3.96100000e+01  1.01822000e+03 -2.15590035e-01]
 ...
 [ 1.85900000e+01  3.95400000e+01  1.00856000e+03 -3.26251737e-01]
 [ 2.29600000e+01  4.50100000e+01  1.01221000e+03 -1.54971652e+00]
 [ 2.05000000e+01  4.96900000e+01  1.00960000e+03 -1.75036989e-01]]
